language: python
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install -U pip wheel coverage codecov
    - pip install -r requirements_dev.txt
    - python setup.py develop
script:
    - flake8 dsfinvk tests
    - isort -rc -c dsfinvk tests
cache:
    directories:
        - $HOME/.cache/pip
